//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcShopping.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mvcdbEntities : DbContext
    {
        public mvcdbEntities()
            : base("name=mvcdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TCategory> TCategory { get; set; }
        public DbSet<TProduct> TProduct { get; set; }
        public DbSet<TProductDetail> TProductDetail { get; set; }
        public DbSet<TSales> TSales { get; set; }
        public DbSet<TStock> TStock { get; set; }
    }
}
