//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcShopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TProduct
    {
        public string id { get; set; }
        public string name { get; set; }
        public int price { get; set; }
        public int cateid { get; set; }
    }
}
